### ISSUE TITLE
RE: Limitations

### ISSUE THREAD

**Issue by ghost** [carlpett/zookeeper_exporter#11]
RE: https://github.com/carlpett/zookeeper_exporter/blob/master/README.md#limitations

Does this mean that I should not run the exporter once for every ZK node, or does it mean I should not run the exporter multiple times per ZK node?

EDIT: I've tried running it once per cluster, but without a mechanism to poll the leader, my graphs have gaps where leader wasn't the destination (load balancer in front of zk).  It would be nice to use zookeeper discovery to identify the leader before polling it.

**Comment by carlpett** [comment]
Hi,
The problem it hints at occurs if you are using multiple Prometheus servers scraping the exporter. Since the stats are reset on each scrape, neither of them would get the full picture.

You should run one exporter instance per ZK node.

**Comment by ghost** [comment]
Thanks!
