### ISSUE TITLE
about zookeeper 3.3.6

### ISSUE THREAD

**Issue by andydodo** [carlpett/zookeeper_exporter#12]
Dear sir，I would like to use the zookeeper_exporter. However my zookeeper is work at 3.3.6 ( zookeeper doesn't upgrade）. How can it compatible with 3.3.6 . Please help me solve this issue

**Comment by carlpett** [comment]
Hi @supremeandy!
Sadly, it is not possible to do so - Zookeeper 3.3 simply does not expose this information in the interface this exporter uses. 
You could have a look at the [jmx_exporter](https://github.com/prometheus/jmx_exporter), perhaps the data is available that way.
