### ISSUE TITLE
How to connect to multiple zookeeper nodes

### ISSUE THREAD

**Issue by wenfei3** [carlpett/zookeeper_exporter#14]
Hi calpett,
thanks for your exporter!
I have 3 zookeeper nodes a1:2181  a2:2181   a3:2181,
and here is the command
```
./zookeeper_exporter -bind-addr ":19141" -log-level "debug" -zookeeper "a1:2181"
```
I found the metrics 
``` 
zk_server_state{state="follower"} 1
# HELP zk_up Exporter successful
# TYPE zk_up gauge
zk_up 1  
```
I thought it means the a1:2181 was up.
How could I know if all of my zk nodes were up?
Thanks for your reply!

**Comment by carlpett** [comment]
Hi @wenfei3,
Happy you find it useful! The design and recommendation is to run one copy of the exporter for each Zookeeper instance, on the same machine as the Zookeeper instance.
This way, you'll have `zk_up` and all the other metrics for each node in you cluster.

**Comment by wenfei3** [comment]
ok,I understand.Thank you!

**Comment by carlpett** [comment]
:+1:
