### ISSUE TITLE
Go Build is failing while trying build 

### ISSUE THREAD

**Issue by vkkothawale** [carlpett/zookeeper_exporter#18]
Hi 
I am getting following error while I am doing go build 
+ go build
prometheus-zookeeper_exporter
./main.go:11:2: imported and not used: prometheus-zookeeper_exporter/vendor/github.com/prometheus/client_golang/prometheus/promhttp"
./main.go:69:28: undefined: prometheus.Handler

Could you please look suggest me changes I am just making binary out of your main.go file using Jenkins ?

**Comment by carlpett** [comment]
Hi @vkkothawale,
In the code in master there isn't an import of promhttp, so you cannot be building directly from the source. Are you working from a fork?

**Comment by vkkothawale** [comment]
Hi @carlpett 
I have fixed that issue by adding promhttp.Handler() instead of  prometheus.Handler() in your source code that worked fine can you please provide me json file file for the zookeeper exporter dashboard for grafana I have check your source code but did not find any json if you can provide that it will great. 
Thanks

**Comment by carlpett** [comment]
Hi,
I'm afraid I do not have any readymade Grafana dashboards. If you make one, please consider contributing it here in a PR!
