### ISSUE TITLE
How to compile exporter?

### ISSUE THREAD

**Issue by fly891583770** [carlpett/zookeeper_exporter#2]
这个zookeepr.go 怎么使用 ？
有步骤吗？
main.go 编译通的过   但是不知道zookeeper.go怎么用

**Comment by fly891583770** [comment]
How do you use this zookeepr.go?

Is there a step?

Main.go compiler pass but do not know how to use zookeeper.go

**Comment by carlpett** [comment]
Hi,
You should not need to compile the files individually, just run `go build` and you should get an executable `zookeeper_exporter` that you can run.

**Comment by fly891583770** [comment]
Hello, I am a rookie you mean direct (build zookeeper_exporter go) on it? The role of main.go and zookeeper.go in the inside is? I looked at the next code zookeeper.go do not know how to run up? Prometheus configuration in zookeeper for prometheus.yml how to configure?

**Comment by carlpett** [comment]
Hi,
What I mean is that to build, these are the only steps you should need:

```
go get github.com/carlpett/zookeeper_exporter
cd $GOPATH/src/github.com/carlpett/zookeeper_exporter
go build
```

After this, you will have a finished binary. The reason for there being multiple files is strictly for reasons of organizing the code, they do not need to be compiled separately.
