### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by StephanErb** [carlpett/zookeeper_exporter#6]
This repository does not ship a license file. It is therefore not clear if it can be used freely. 

Prometheus is licensed under Apache 2.0. I would therefore propose to use the same license here as well.

Thanks,
Stephan

**Comment by carlpett** [comment]
@StephanErb Thanks! Apparently I forgot when I created the repo, sorry about that. 
I typically use the MIT license, hope that is acceptable as well.

**Comment by StephanErb** [comment]
That was quick. Thanks!
