### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by SabaPing** [carlpett/zookeeper_exporter#9]
I have a zk cluster with 5 nodes. I deployed zookeeper_exporter to all nodes, using command 
```
sudo nohup path_to_zookeeper_exporter &
```
with no additional arguements.
I frequently encounter the following bug(exporter crashed):
```
time="2017-08-24T16:09:29+08:00" level=info msg="Starting zookeeper_exporter"
time="2017-08-24T16:09:29+08:00" level=info msg="Starting metric http endpoint on :9141"
time="2017-08-24T16:09:34+08:00" level=info msg="Fetching metrics from Zookeeper"
panic: runtime error: index out of range

goroutine 31 [running]:
main.(*zookeeperCollector).Collect(0xc420011ec0, 0xc420148360)
        /home/qunheadmin/go/src/github.com/carlpett/zookeeper_exporter/zookeeper.go:154 +0x59d
github.com/carlpett/zookeeper_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func2(0xc4200fa400, 0xc420148360, 0x8978e0, 0xc420011ec0)
        /home/qunheadmin/go/src/github.com/carlpett/zookeeper_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:433 +0x61
created by github.com/carlpett/zookeeper_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather
        /home/qunheadmin/go/src/github.com/carlpett/zookeeper_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:434 +0x2ec
time="2017-08-24T16:15:29+08:00" level=info msg="Starting zookeeper_exporter"
time="2017-08-24T16:15:29+08:00" level=info msg="Starting metric http endpoint on :9141"
time="2017-08-24T16:15:34+08:00" level=info msg="Fetching metrics from Zookeeper"
panic: runtime error: index out of range

goroutine 52 [running]:
main.(*zookeeperCollector).Collect(0xc4200fa7c0, 0xc42005e9c0)
        /home/qunheadmin/go/src/github.com/carlpett/zookeeper_exporter/zookeeper.go:154 +0x59d
github.com/carlpett/zookeeper_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func2(0xc420011b00, 0xc42005e9c0, 0x8978e0, 0xc4200fa7c0)
        /home/qunheadmin/go/src/github.com/carlpett/zookeeper_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:433 +0x61
created by github.com/carlpett/zookeeper_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather
        /home/qunheadmin/go/src/github.com/carlpett/zookeeper_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:434 +0x2ec
```
Sometimes this bug occurs right after I start exporter. Sometimes it occurs after a long period(more than one day).

Any thoughts about this? Thanks.

**Comment by SabaPing** [comment]
I find the problem. The reason is that my zk node is down. When you send a "mntr" request, you get an empty string. You split is and access the 2nd element, boom!
However, I think you could catch this exception in your code to avoid exporter crash.

**Comment by carlpett** [comment]
Thanks for reporting! And also for finding the problem :) I agree, zookeeper being unavailable should not cause the exporter to crash. I'll fix that.

**Comment by carlpett** [comment]
@BBQyuki Hm, actually, this seems a bit strange. The code already handles the case where the zk node is not listening on the expected port. So in your case the node appears to be up and having the socket open, but not responding properly? Still a bug, of course, just wanted to understand when this is happening.

**Comment by carlpett** [comment]
There was a missing error handling case when it was possible to connect, but the writes failed. This is fixed in above pull request. Also added some handling for cases where the returned data is not parseable (which would also have fixed the symptoms you were seeing)

**Comment by SabaPing** [comment]
@carlpett Thanks for the reply and bug fix :smile:
